/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lp;

import lp.HotelCachorros.Acomodacao;
import lp.HotelCachorros.Especie;
import lp.HotelCachorros.Persistencia.BancoDeDados;
import lp.HotelCachorros.Porte;
import lp.HotelCachorros.PorteFaixa;
import lp.view.CheckInView;
import lp.view.CheckOutView;
import lp.view.ConsultaAcomodacaoView;
import lp.view.Relatorio;

/**
 *
 * @author vanderson
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        criaFaixasDePorte();
        criarAcomodacoes();
    }

    private void criaFaixasDePorte() {
        PorteFaixa f1 = new PorteFaixa(0d, 20d, 0d, 30d, Especie.Cachorro,
                Porte.Pequeno);
        PorteFaixa f2 = new PorteFaixa(21d, 40d, 31d, 60d, Especie.Cachorro,
                Porte.Medio);
        PorteFaixa f3 = new PorteFaixa(41d, 60d, 61d, 80d, Especie.Cachorro,
                Porte.Grande);
        BancoDeDados.getInstance().getPortesFaixas().add(f1);
        BancoDeDados.getInstance().getPortesFaixas().add(f2);
        BancoDeDados.getInstance().getPortesFaixas().add(f3);
    }
    private int numAcomodacoesGrandes = 3;
    private int numAcomodacoesMedias = 2;
    private int numAcomodacoesPequenas = 5;

    private void criarAcomodacoes() {
        Acomodacao grandes[] = new Acomodacao[numAcomodacoesGrandes];
        Acomodacao medias[] = new Acomodacao[numAcomodacoesMedias];
        Acomodacao pequenas[] = new Acomodacao[numAcomodacoesPequenas];
        int i;
        for (i = 0; i < grandes.length; i++) {
            grandes[i] = new Acomodacao(i,Porte.Grande,Especie.Cachorro);
            BancoDeDados.getInstance().getAcomodacoes().add(grandes[i]);
        }
        for (i = 0; i < medias.length; i++) {
            medias[i] = new Acomodacao(i+numAcomodacoesGrandes,Porte.Medio,Especie.Cachorro);
            BancoDeDados.getInstance().getAcomodacoes().add(medias[i]);
        }
        for (i = 0; i < pequenas.length; i++) {
            pequenas[i] = new Acomodacao(i+numAcomodacoesGrandes+numAcomodacoesMedias,
                    Porte.Pequeno,Especie.Cachorro);
            BancoDeDados.getInstance().getAcomodacoes().add(pequenas[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkInButton = new javax.swing.JButton();
        imprimirRelatorioButton = new javax.swing.JButton();
        consultarAcomodacaoButton = new javax.swing.JButton();
        checkOutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel animais");

        checkInButton.setText("Check-in");
        checkInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInButtonActionPerformed(evt);
            }
        });

        imprimirRelatorioButton.setText("Imprimir relatório");
        imprimirRelatorioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirRelatorioButtonActionPerformed(evt);
            }
        });

        consultarAcomodacaoButton.setText("Consultar acomodação");
        consultarAcomodacaoButton.setToolTipText("");
        consultarAcomodacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAcomodacaoButtonActionPerformed(evt);
            }
        });

        checkOutButton.setText("Check-out");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Hotel de animais");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imprimirRelatorioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultarAcomodacaoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(206, 206, 206))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(checkInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imprimirRelatorioButton)
                .addGap(18, 18, 18)
                .addComponent(consultarAcomodacaoButton)
                .addGap(18, 18, 18)
                .addComponent(checkOutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarAcomodacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAcomodacaoButtonActionPerformed
        ConsultaAcomodacaoView view = new ConsultaAcomodacaoView();
        view.setDefaultCloseOperation(CheckInView.DISPOSE_ON_CLOSE);
        view.show();
    }//GEN-LAST:event_consultarAcomodacaoButtonActionPerformed

    private void checkInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInButtonActionPerformed
        CheckInView view = new CheckInView();
        view.setDefaultCloseOperation(CheckInView.DISPOSE_ON_CLOSE);
        view.show();
    }//GEN-LAST:event_checkInButtonActionPerformed

    private void imprimirRelatorioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirRelatorioButtonActionPerformed
        Relatorio view = new Relatorio();
        view.setDefaultCloseOperation(CheckInView.DISPOSE_ON_CLOSE);
        view.show();
    }//GEN-LAST:event_imprimirRelatorioButtonActionPerformed

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
        CheckOutView view = new CheckOutView();
        view.setDefaultCloseOperation(CheckInView.DISPOSE_ON_CLOSE);
        view.show();
    }//GEN-LAST:event_checkOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkInButton;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JButton consultarAcomodacaoButton;
    private javax.swing.JButton imprimirRelatorioButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
